### ISSUE TITLE
Applicable for Fragment?

### ISSUE THREAD

**Issue by vintrecenio** [mingdroid/SETransitionDemo#1]
I love your codes! They're perfect! But one thing I wanna ask is, can I apply those transitions from Fragment as the source instead of an Activity? Below codes seems not working inside a Fragment:

    @Override
    public void onActivityReenter(int resultCode, Intent data) {
        super.onActivityReenter(resultCode, data);
        if (resultCode == RESULT_OK && data != null) {
            exitPosition = data.getIntExtra("exit_position", enterPosition);
        }
    }

**Comment by mingdroid** [comment]
you can use a singleton class to store the exitPosition, it doesn't matter.
This is important:
```
setExitSharedElementCallback(new SharedElementCallback() {
            @Override
            public void onMapSharedElements(List<String> names, Map<String, View> sharedElements) {
                if (exitPosition != enterPosition &&
                        names.size() > 0 && exitPosition < sharedViews.length) {
                    names.clear();
                    sharedElements.clear();
                    View view = sharedViews[exitPosition];
                    names.add(view.getTransitionName());
                    sharedElements.put(view.getTransitionName(), view);
                }
                setExitSharedElementCallback((SharedElementCallback) null);
                sharedViews = null;
            }
        });
```
